### ISSUE TITLE
Hata

### ISSUE THREAD

**Issue by dBerkeTurkmen** [aflextr/animecix-stremio-addon#1]
https://i.imgur.com/tBfQ7cZ.png

**Comment by aflextr** [comment]
> https://i.imgur.com/tBfQ7cZ.png

Arama yerinin en sonuna animecix yada ax veyahut ac yazarsanız çalışır.

![image](https://github.com/aflextr/animecix-stremio-addon/assets/53778891/137f7a17-1826-47fe-b492-a782bfc61bdd)
